kind: PersistentVolume
apiVersion: v1
metadata:
  name: financedb-volume
  labels:
    type: local
    app: financedb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: financedb-claim
  labels:
    app: financedb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
